### ISSUE TITLE
start key binding not cleared when clearing keybindings

### ISSUE THREAD

**Issue by lilydjwg** [jordansissel/keynav#7]
There's a global `/etc/keynavrc` and a personal `~/.keynavrc`, and they are parsed in order. I clear all previous key bindings to define my own in `~/.keynavrc`. However, the global 'start' keybinding is still there although it does nothing.

**Comment by sojusnik** [comment]
It would be much better, if `~/.keynavrc` would completely override `/etc/keynavrc`, so that only specified combinations in `~/.keynavrc` would trigger events, and not also the default ones from `/etc/keynavrc`.

**Comment by lilydjwg** [comment]
This issue should have been fixed by #14.

**Comment by sojusnik** [comment]
According to `locate keynavrc` my only keynavrc file lies in `~/.keynavrc` and the other one is found under `/usr/share/doc/keynav/keynavrc`, but noneoftheless the default keybindings are still working. Didn't try to implement your commit, because I'm using another version, but do you think, that your commit will solve this too?

**Comment by lilydjwg** [comment]
If you have the `clear` command at the top of your config, I suppose it will work. I don't quite remember the whole thing though.

**Comment by sojusnik** [comment]
Thanks for this hint. That did the trick!
